# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_report_analytics_metrics_per_location_index:
    pattern:  /report/analytics/metricsperlocation/{id}
    defaults: { _controller: CampaignChainReportAnalyticsMetricsPerLocationBundle:Page:index, id: 0 }
    methods:  [GET]

campaignchain_report_analytics_metrics_per_location_location:
    pattern:  /report/analytics/metricsperlocation/location/{id}
    defaults: { _controller: CampaignChainReportAnalyticsMetricsPerLocationBundle:Page:location, id: 0 }