# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

services:
    campaignchain.report.analytics.metrics_per_location.data:
        class: CampaignChain\Report\Analytics\MetricsPerLocationBundle\Util\Data
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@campaignchain.core.serializer.default'
